### ISSUE TITLE
Upgrade to pairing >= 0.15?

### ISSUE THREAD

**Issue by huitseeker** [poanetwork/threshold_crypto#100]
Version 0.15 of pairing is out, and has upgraded the whole zkcrypto suite of dpeendencies, including a fresh rand 0.7 (yay!).

However, ff in this version has removed u128 support:
https://github.com/zkcrypto/ff/commit/0eb9f5040b8d24703392ba23798347a1163ce802

Opening this issue to start attracting attention to the challenge of upgrading the pairing dependency in threshold-crypto.

**Comment by afck** [comment]
See #93.
