### ISSUE TITLE
Is full PublicKeySet really needed to combine signature/decryption shares?

### ISSUE THREAD

**Issue by madadam** [poanetwork/threshold_crypto#103]
It seems the only piece of info used is the threshold: https://github.com/poanetwork/threshold_crypto/blob/master/src/lib.rs#L606, https://github.com/poanetwork/threshold_crypto/blob/master/src/lib.rs#L616

Would an alternative API that only takes the threshold make sense?
```rust
fn combine_signatures<'a, T, I>(threshold: usize, shares: I) -> Result<Signature>
    where I: IntoIterator<Item = (T, &'a SignatureShare)>, ... 
{}

fn decrypt<'a, T, I>(threshold: usize, shares: I) -> Result<Vec<u8>>
    where I: IntoIterator<Item = (T, &'a DecryptionShare)>, ... 
{}
```
This way people wouldn't have to store the full `PublicKeySet` which is kind of expensive.

Would you guys accept a PR implementing this?

**Comment by afck** [comment]
That makes sense. I'm happy to review it.

But note that to _validate_ signature shares you still need the `PublicKeySet`. And if you don't validate them and a combined signature doesn't match, you don't know which of the shares was wrong.

**Comment by madadam** [comment]
That's a good point which I didn't consider and which makes this whole idea significantly less useful for our needs. Closing the issue for now.

**Comment by niko-ng** [comment]
Hello,
It seems that eventually @afck backtracked on the uselessness of this proposal. 
I am also considering that only the threshold (degree of the commitment) is needed in order to combine_signatures.

It seems no change in the API was made eventually.
Would you consider adding the APIs that @madadam proposed?

**Comment by afck** [comment]
(Sorry, I'm not on this project anymore. Not sure if it's currently maintained.)

**Comment by niko-ng** [comment]
Thanks for your feedback! I will create a fork and publish it to crates.io, as the maintainer seems to have disappeared.
