### ISSUE TITLE
Question: Any plans for updating pairing?

### ISSUE THREAD

**Issue by vihu** [poanetwork/threshold_crypto#113]
Hello, I was wondering if the maintainers have any plans for updating pairing and bls12-381 libraries for this repository. The reason I ask is because I'm having a bit of tough time implementing [Aggregate Signatures](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-02#section-2.9) using the primitives defined here.

The authors of [pairing](https://github.com/zkcrypto/pairing) and [bls12-381](https://github.com/zkcrypto/bls12_381) have separated the codebase of those two repos, and pairing now is just a collection of types and traits whereas bls12-381 has the curve definition.

[Here's](https://github.com/vihu/threshold_crypto/pull/6) my broken aggregate signature work if anyone is interested, I'm basically stuck on trying to find the right methods to calculate identity element in Gt and doing the subsequent operations to do `core_aggregate_verify` as mentioned in the IETF specification.

**Comment by afck** [comment]
I'm not sure if anyone is actively working on this crate, sorry.

**Comment by vihu** [comment]
> I'm not sure if anyone is actively working on this crate, sorry.

Oh I see, thanks for the reply anyway. I will continue to power through this ordeal [myself](https://github.com/helium/threshold_crypto/pull/7).
