### ISSUE TITLE
TODO: Add a basic Readme

### ISSUE THREAD

**Issue by c0gent** [poanetwork/threshold_crypto#2]
@vkomenda I've been told you may already be handling this or at least you have an example you want to use already but I'm happy to help if you can show me which example you want to use.

Or I'll just make something up :P

**Comment by andogro** [comment]
A general outline for this README...  a lot will hinge on the nature of the example.

**Comment by andogro** [comment]
Basic README outline - will hinge on nature of the example. 

Description

Threshold Crypto provides constructors for encrypted message distribution over a public network. We utilize the `pairing` elliptic curve library for public and private key share operations. In a network environment, messages are signed and encrypted, and key and signature shares are distributed to network participants. A message can be decrypted and verified only with cooperation from any subset of `threshold + 1` network participants. 

Installation / Usage

- Parameters, parameter generation
  - threshold, signatures, message?
- Example Use Case

Testing

License

Contributing

**Comment by c0gent** [comment]
I was going to make a pretty standard Rust library readme with the usual sections, something I've done many times (https://github.com/cogciprocate/ocl, https://github.com/cogciprocate/voodoo, etc.).

I'll certainly consult you for approval before merging it @andogro  :)

**Comment by c0gent** [comment]
I'll be sure to copy CONTRIBUTING into the repo and add a link, etc.

**Comment by andogro** [comment]
sure, let me know how I can help as needed.

**Comment by c0gent** [comment]
Will do, I'll sumbit a PR for it as soon as we figure out what example we want to use.

**Comment by c0gent** [comment]
I hope I'm not stepping on your toes here by the way. If you have it under control just wave me off. I'm not used to having a dedicated writer available! :)

**Comment by afck** [comment]
I'd probably put the introductory text like this:

This is a [threshold cryptosystem](https://en.wikipedia.org/wiki/Threshold_cryptosystem) for collaborative decryption and signatures: Choose a threshold value _t_, create a key set, distribute _N_ secret key shares among the participants and publish the public master key. A third party can now encrypt a message to the public master key, and any set of _t + 1_ participants—but no fewer!—can collaborate to decrypt it. Also, any _t + 1_ participants can collaborate to sign a message, producing a signature that can be verified against the public master key.

One application is distributed networks that need to tolerate up to _t_ adversarial nodes: It requires _t + 1_ nodes to reveal information encrypted to the network (the master key), or to produce information signed by the network, so it can be trusted by a third party.

This cryptosystem has the property that signatures are unique, i.e. independent of which particular participants produced it. If S1 and S2 are signatures for the same message, produced by two different sets of _t + 1_ secret key share holders each, then they won't just both be valid, but in fact equal. This is useful in some applications, for example it allows using the signature of a message as a pseudorandom number that is unknown to anyone until _t + 1_ participants agree to reveal it.

In its simplest form, threshold cryptography requires a trusted dealer who produces the secret key shares and distributes them. However, there are ways to produce the keys themselves in a way that guarantees that nobody except the corresponding participant knows their secret in the end, and this crate includes the basic tools to implement such a Distributed Key Generation scheme.

**Comment by afck** [comment]
For usage examples, maybe some of the tests could be adapted:
* `test_simple_sig`, `test_threshold_sig` for signing.
* `test_simple_enc`, `test_threshold_enc` for encrypting and decrypting.
* `poly::distributed_key_generation` for distributed key generation.
