### ISSUE TITLE
Change the license to MIT/Apache-2.0 by popular vote

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/threshold_crypto#7]
The provisional GNU GPL license is too strong for this library and should be replaced with a more permissive one. MIT/Apache-2.0 has been chosen as a suitable candidate.

**Comment by c0gent** [comment]
All contributors to this project, (@afck, @vkomenda, @DrPeterVanNostrand, @mbr, @c0gent) should probably reply in this thread with *"I approve the license change to MIT/Apache-2.0"*.

I approve the license change to MIT/Apache-2.0.

**Comment by vkomenda** [comment]
I approve the license change to MIT/Apache-2.0.

**Comment by afck** [comment]
I approve the license change to MIT/Apache-2.0.

**Comment by DrPeterVanNostrand** [comment]
I approve the license change to MIT/Apache-2.0.

**Comment by DrPeterVanNostrand** [comment]
Oh, sorry about that.

**Comment by mbr** [comment]
I approve the license change to MIT/Apache-2.0.
