### ISSUE TITLE
Where is gen04() implemented

### ISSUE THREAD

**Issue by trustyrust** [poanetwork/threshold_crypto#80]
I am having difficulty understanding how/where gen04() is implemented. gen04 is not a standard function on the ChaChaRng, and it seems to return polymorphic types, e.g.

let fr: Fr = rng.gen04();
let g2: G2 = rng.gen04();

Can you explain how/where it is defined?

**Comment by DrPeterVanNostrand** [comment]
Hey, it's a trait method on `rand04_compat::RngExt`.

https://github.com/poanetwork/rand04_compat/blob/master/src/lib.rs#L33
