### ISSUE TITLE
Publish threshold_crypto 0.3.2?

### ISSUE THREAD

**Issue by nbaksalyar** [poanetwork/threshold_crypto#88]
There have been some changes implementing common traits for `SerdeSecret` and `Copy` for `PublicKeyShare` which are not a part of a published crate just now. Because of that, we're using `threshold_crypto` as a git dependency which prevents publishing newer versions of our crates.

Could you please update the published crate?

**Comment by afck** [comment]
It's published now: https://crates.io/crates/threshold_crypto/0.3.2
